name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Set up GCC
      run: sudo apt-get install -y g++

    - name: Build
      run: g++ -o test ARP_DN1_PROG/ARP_DN1_PROG.cpp

    - name: Run Tests
      run: |
        echo "Running tests and collecting outputs..."
        ./test 0 'IIIII' primer_besedilo.txt
        cat out.txt >> tests.txt
        echo "" >> tests.txt

        ./test 1 'IIIII' primer_besedilo.txt
        cat out.txt >> tests.txt
        echo "" >> tests.txt

        ./test 0 'III' primer_besedilo.txt
        cat out.txt >> tests.txt
        echo "" >> tests.txt

        ./test 1 'III' primer_besedilo.txt
        cat out.txt >> tests.txt
        echo "" >> tests.txt

        ./test 0 'lorem ipsum' primer_besedilo.txt
        cat out.txt >> tests.txt
        echo "" >> tests.txt

        ./test 1 'lorem ipsum' primer_besedilo.txt
        cat out.txt >> tests.txt

    - name: Upload Tests Output
      uses: actions/upload-artifact@v4
      with:
        name: tests-output
        path: tests.txt
