name: Deploy
on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
      # Makes it go when test is complete
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    # Checks if the test was successful
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # Gets the current code onto the runner
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # Set up an image for buildx
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      # Log into docker
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: thecoffeeaddict/arp_dn1:latest
      # Push onto docker